Metatavu/kunta-api-www-mikkeli

views/includes/nav.pug, views/pages/index.pug
=> Resolved #1

routes/index.js, views/pages/contents.pug
=> Implemented sidebar contents

routes/index.js, views/pages/index.pug
=> Feature #3 announcements

routes/index.js, views/pages/contents.pug
=> Replaced siblings listing with child pages listing

routes/index.js, views/pages/index.pug
=> Removed contents and added date into front page announcements list

routes/index.js, scss/announcements.scss, views/pages/announcement.pug, views/pages/index.pug, views/pages/news-article.pug
=> Feature #12 announcement page

.scss-style.yml, package.json, public/js/common.js, routes/index.js, scss/styles.scss, views/ajax/search.pug
=> Feature #16 search

routes/index.js
=> Fixed file downloading from autocomplete search

routes/index.js, scss/contents-common.scss
=> Responsive sidebar

views/pages/index.pug
=> fixed mikkelinyt link

routes/index.js
=> Fixed event orderinig

views/pages/contents.pug, views/pages/news-article.pug
=> Hide sidebar if there is no content

views/includes/mixins.pug
=> Removed >>

public/js/contents.js, routes/index.js, views/pages/contents.pug
=> Changed content images to be loaded lazyly

views/pages/index.pug
=> Removed abstract from news

routes/index.js, views/includes/mixins.pug
=> Changed active menu to automatically open child item list

routes/index.js, scss/index.scss, views/pages/index.pug
=> Changed banner texts to respect color attributes

routes/index.js, scss/styles.scss
=> Fixed logo position

views/pages/index.pug
=> Added participate and affect page

routes/index.js
=> Changed page banners to be streamed from api

views/includes/nav.pug
Altered layout a bit to accomodate also linkedin button
fixes #66
=> Fixed social media buttons

public/js/index.js, scss/index.scss, views/pages/index.pug
=> Automatically scale tile header fonts to fit to container

scss/styles.scss
=> Changed footer links to be white

views/includes/nav.pug
=> Changes social media buttons to open new tab

scss/index.scss
=> Made static header with max width

public/js/contents.js, scss/contents.scss
=> Changed casem history topics to be hidden by default

scss/contents-common.scss, scss/styles.scss, views/layout/contents.pug, views/layout/index.pug, views/layout/news.pug
=> Hotfix #81 side scroll

.gitignore, index.js, public/js/timetables.js, routes/index.js, scss/timetables.scss, views/ajax/timetable.pug, views/includes/timetable-head.pug, views/layout/timetables.pug, views/pages/timetable.pug
=> Added implementation for timetable view

public/js/timetables.js, views/pages/timetable.pug
=> Changed tiles to be loaded with ssl

public/js/timetables.js
=> Render map after document has been properly loaded

routes/index.js, routes/shortlinks/index.js
=> Added support for shortlinks

routes/banners/index.js, routes/common/index.js, routes/events/index.js, routes/index.js, routes/pages/index.js, routes/tiles/index.js
=> Feature #70 stream images

public/js/timetables.js, scss/timetables.scss, views/pages/timetable.pug
=> Added loader image and tweaked map script

routes/common/index.js, routes/publictransport/index.js
=> Optimized timetable view

public/js/timetable-create.js, public/js/timetables.js, routes/publictransport/index.js, scss/timetables.scss, views/pages/timetable-create.pug, views/pages/timetable.pug
=> Added support for specifying map zoom

routes/announcements/index.js, routes/common-data/index.js, routes/common/index.js, routes/error/index.js, routes/files/index.js, routes/index.js, routes/jobs/index.js, routes/news/index.js, routes/redirect/index.js, routes/root/index.js, routes/search/index.js, views/pages/index.pug
=> Feature #107 route files

routes/news/index.js, routes/root/index.js, scss/news-list.scss, scss/news.scss, views/pages/news-article.pug, views/pages/news-list.pug
=> News by tags view and image streaming

routes/pages/index.js, views/pages/contents.pug
=> Removed default featured image from pages

public/js/common.js
=> Highlight also parents of open menu item

scss/contents-common.scss
=> Changed menu item gaps to be smaller

scss/index.scss, views/pages/index.pug
=> Removed silhouette from front page

public/js/news-list.js, routes/news/index.js, scss/news-list.scss, views/pages/news-list.pug
=> Changed news tags list to use single column layout

scss/index.scss, views/pages/index.pug
=> Added popular box into index banner

routes/common/index.js, routes/index.js, routes/search/index.js
=> Added max results parameter to page search and file search modules

routes/common/index.js
=> Process kunta-api images

routes/common-data/index.js, views/includes/head.pug
=> Added google analytics support

scss/contents.scss
=> Added styles for service hours

routes/common/index.js, routes/news/index.js, scss/news-list.scss, views/pages/index.pug, views/pages/news-list.pug
=> Added view for listing all news

routes/search/index.js, views/ajax/menu-search.pug, views/ajax/search-news.pug
=> Added support for searching news

routes/common/index.js
=> Added null-check into common module htmlToText method

routes/incidents/index.js, routes/index.js, views/includes/head.pug
=> Added incidents

public/js/index.js, routes/root/index.js, scss/index.scss, views/pages/index.pug
=> Added a script for scaling oversized tile texts

routes/common-data/index.js, views/includes/head.pug
=> Made incidents configurable

package.json, public/js/common.js, routes/common-data/index.js, views/includes/head.pug, views/includes/mixins.pug, views/pages/contents.pug
=> Feature #170 readspeaker

scss/index.scss
=> Fixed tile and news colors

views/includes/head.pug
=> Added support for incident css

routes/common/index.js
=> Added size parameter into content images

views/pages/news-list.pug
=> Hotfix #218 all news text overflow

views/includes/mixins.pug, views/pages/announcement.pug, views/pages/jobs.pug, views/pages/news-article.pug
=> Fixed encoding in several menus

scss/_fonts.scss, scss/_icons.scss, scss/_vars.scss, scss/styles.scss, scss/timetable-create.scss, scss/timetables.scss
=> Changed ultra font to Cairo

scss/index.scss
=> Fixed font scaling in banner and tiles

routes/common-data/index.js, views/includes/head.pug
=> Added support for live chat

public/js/news-article.js, routes/news/index.js, routes/pages/index.js, scss/contents.scss, scss/news.scss, views/pages/contents.pug, views/pages/news-article.pug
=> Images are now scaled horizontally

public/js/announcements-list.js, routes/announcements/index.js, scss/_colors.scss, scss/announcements-list.scss, scss/common-list.scss, views/pages/announcements-list.pug, views/pages/index.pug
=> Feature #223 announcements list

public/js/index.js, scss/index.scss, views/pages/index.pug
=> Fixed event image scaling

views/pages/index.pug
=> Overlay is not generated if tile has no title or content

public/js/contents.js
=> Added support for customizing contact search placeholder text

views/pages/index.pug
=> Changed Kuntarekry -> Avoimet työpaikat

routes/common/index.js, routes/contacts/index.js, routes/search/index.js
=> Changed searches to tokenize search strings and add wildcards

routes/search/index.js
=> Feature #261 tokenize search

routes/announcements/index.js
=> Fixes issue #265

routes/contacts/index.js
=> Fixed issue #267

scss/contents.scss
=> Fixed issue #279

scss/_vars.scss, scss/contents-common.scss, scss/contents.scss
=> Fixed #282

routes/announcements/index.js
=> Added list breadcrumb into announcement view

routes/announcements/index.js, views/pages/announcement.pug
=> Removed sidebar from announcements

routes/announcements/index.js, routes/common/index.js, views/pages/announcement.pug
=> Hotfix #285 sidebar images

routes/common/index.js, routes/news/index.js, routes/pages/index.js
=> Fixed issue #292

routes/common/index.js
=> Stripped non visible elements from search excerpt

public/js/mikkelin-tarina.js
=> Fixed issue #301

public/js/mikkelin-tarina.js
=> Added url encoding

routes/news/index.js, views/pages/news-article.pug
=> Added disgus support

views/pages/mikkelin-tarina-result.pug
=> Resolved #311

scss/styles.scss
=> Changed text color

public/js/common.js
=> url encode search

routes/root/index.js
=> Removed limit of tiles

routes/root/index.js, scss/contents-common.scss, scss/search.scss
=> Hotfix #340 list dot bug

public/js/search.js, routes/root/index.js, scss/contents-common.scss, scss/search.scss
=> Hotfix #342 ie link bug

package-lock.json, package.json, public/js/news-list-widget.js, scss/contents-common.scss, views/includes/head.pug
=> Generalized news list widget

routes/common-data/index.js, scss/styles.scss, views/includes/nav.pug
=> Added support for switching locales

.eslintrc.json, .hound.yml, routes/pages/index.js, views/pages/contents.pug
=> Added support for localized root pages

routes/common/index.js, scss/contents.scss, views/fragments/small-page-banner.pug
=> Added support for small page banners

.scss-style.yml, public/js/news-list-widget.js, scss/contents-common.scss
=> Added support for text mode in emdedded news lists

public/js/common.js, scss/styles.scss, views/includes/nav.pug
=> Changed locale menu to be dropdown

routes/common/index.js, routes/search/index.js
=> Hotfix 368 shy

package-lock.json, scss/contents.scss, views/fragments/small-page-banner.pug
=> Hotfix 376 fix gutters on small banners

package.json, public/js/contents.js, scss/_colors.scss, scss/_vars.scss, scss/contents-common.scss
=> requested style changes

scss/contents-common.scss
=> style changes

scss/styles.scss
=> Fixed header h4 font

views/includes/nav.pug
=> Added support for changing page when changing locale

scss/styles.scss
=> Changed 100vw to 100%

routes/common/index.js, routes/root/index.js
=> Switched events source

package-lock.json, package.json, routes/contacts/index.js, views/pages/index.pug
=> Contacts from URL

package-lock.json, package.json, routes/redirect/index.js
=> Hotfux 416 search links broken

public/js/contents.js
=> Widgets are now defined after document is ready in content.js

views/pages/announcement.pug
=> Added readspeaker for announcements

routes/contacts/index.js
=> Added orgainzation units into contact search

package-lock.json, package.json, public/js/search.js, routes/search/index.js, views/ajax/menu-search.pug, views/ajax/search-wp-pages.pug, views/pages/search.pug
=> Feature 432 search for oppiminen.mikkeli.fi

package-lock.json, routes/root/index.js
=> Hard coded
